<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TvStream extends Model
{
    use HasFactory;
    protected $fillable = [
        'code',
        'category_code',
        'menu_code',
        'channel_code',
        'genre_code',
        'rating_code',
        'quality_code',
        'tag_code',
        'person_code',
        'cast_code',
        'writer_code',
        'director_code',
        'producer_code',
        'show_code',
        'season_code',
        'app_code',
        'episode',
        'title',
        'url',
        'ad_url',
        'stream_dai_key',
        'playing_method',
        'poster',
        'poster_sdm',
        'poster_portrait',
        'poster_square',
        'qr_code',
        'qr_code_url',
        'banner_poster',
        'thumbnail',
        'short_description',
        'long_description',
        'released_date',
        'available_date',
        'expiration_date',
        'trailer_url',
        'duration',
        'second',
        'featured',
        'home_featured',
        'type',
        'content_type',
        'ad_type',
        'external_ad',
        'premium',
        'monetization_type',
        'plan_duration',
        'plan_period',
        'amount',
        'show_tv_guide',
        'order',
        'start_date',
        'start_time',
        'end_date',
        'end_time',
        'password',
        'trending_start_date',
        'trending_start_time',
        'trending_hours',
        'trending_days',
        'trending_weeks',
        'distributor_id',
        'content_owner_id',
        'advisory_code',
        'language_code',
        'status'
    ];
}
